### ISSUE TITLE
【期望】接入千帆支持的大模型

### ISSUE THREAD

**Issue by Ikaros-521** [jm12138/WenxinWorkshop-Python-SDK#1]
如题，如llama等

**Comment by jm12138** [comment]
其实应该是可以直接用的，url换成llama的比如 https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/llama_2_7b

```python
erniebot = LLMAPI(
    api_key=api_key,
    secret_key=secret_key,
    url='https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/llama_2_7b'
)
```

**Comment by jm12138** [comment]
后续会跟着千帆的更新，更新一下其他功能的，function call 之类的，有空的话

**Comment by Ikaros-521** [comment]
> 其实应该是可以直接用的，url换成llama的比如 https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/llama_2_7b
> 
> ```python
> erniebot = LLMAPI(
>     api_key=api_key,
>     secret_key=secret_key,
>     url='https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/llama_2_7b'
> )
> ```

好好好

**Comment by Ikaros-521** [comment]
https://github.com/Ikaros-521/WenxinWorkshop-Python-SDK
改了点，实测可用
